### ISSUE TITLE
Menu pop-up

### ISSUE THREAD

**Issue by xen-42** [Outer-Wilds-New-Horizons/new-horizons#167]
### Feature

- List changes after a new update
- Give a warning if any json files did not load successfully
- If a addon is tagged as being `stand-alone` (we'll need a config file for add-on settings for this) and other add-ons are detected, it will inform you that this goes against what the creator wanted (but still let you play)

**Comment by FreezeDriedMangos** [comment]
some story mods have planned sequels, so it would also be neat to add a param that lets you list mods that are excluded from the "stand-alone" check

**Comment by xen-42** [comment]
In the end, said no to change logs (would be too long anyway). Instead addons can have a popup that will be displayed once, and we'll give the popup warning for files that failed to load.
