### ISSUE TITLE
Preserve items when warping

### ISSUE THREAD

**Issue by xen-42** [Outer-Wilds-New-Horizons/new-horizons#192]
### Feature

Just like, don't destroy on load it or something.

Track what the original item was so that if you bring it back to the original system after it doesn't get duplicated.

Anything that has extra info on it (slide reels and scrolls) have them get destroyed.

**Comment by MegaPiggy** [comment]
![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/34462599/c112da12-c4b8-4259-911c-a004c666df48)

**Comment by xen-42** [comment]
Main issue would be with removing a thing from a socket, and then ensuring its still removed when the system gets reloaded

**Comment by xen-42** [comment]
Relates to #952 in that the state of the warp core should also be tracked similarly
