### ISSUE TITLE
Share shiplog option for Custom Solar Systems

### ISSUE THREAD

**Issue by TextureTurtle** [Outer-Wilds-New-Horizons/new-horizons#193]
### Feature

Instead of having it's own menu, have an option for the shiplogs to be shared

### Context

If the solar system logs have stuff that link to the base game is would be nice for those 2 to be connected

**Comment by xen-42** [comment]
no

**Comment by xen-42** [comment]
Okay fine maybe

**Comment by xen-42** [comment]
Now that mindscapes has essentially used custom code to implement this themselves, I'm closing this issue and saying we will not natively support it.
