### ISSUE TITLE
Make it so you can knock custom satellites out of orbit

### ISSUE THREAD

**Issue by xen-42** [Outer-Wilds-New-Horizons/new-horizons#194]
### Feature

Make it so you can push them like with the map satellite in base game.

### Context

Issue is that rigidbodies cant have concave colliders or whatever. Either we have that as an annoying limitation that most users won't understand, or we create some custom way of detecting collisions between the satellite and the player and applying the proper forces to the satellite. And by "either" I mean we 100% do the latter.

**Comment by xen-42** [comment]
Nvm let's have it be an annoying limitation actually

**Comment by TextureTurtle** [comment]
Nah that limitation is completely fine considering that people would just need to make a compound collider using convex colliders/primitives.

**Comment by xen-42** [comment]
Fixed in 1.14.1
