### ISSUE TITLE
More vection fields

### ISSUE THREAD

**Issue by TerrificTrifid** [Outer-Wilds-New-Horizons/new-horizons#219]
### Feature

Replace hasRain/hasSnow with vectionFields, either an array of strings, or maybe a new module with all the options as curves. The former is probably enough, but the latter would give helpful control of heights.

Options would be rain, snow, embers, sand, leaves, fireflies, and bramble bugs.

**Comment by MegaPiggy** [comment]
There is also plankton, bubbles, and other stuff like that.

**Comment by TerrificTrifid** [comment]
Also an option to multiply the quantity
