### ISSUE TITLE
BlackHole Ambience Pitch

### ISSUE THREAD

**Issue by RidgePain** [Outer-Wilds-New-Horizons/new-horizons#226]
### What Happened?

The BlackHole curve attribute doesn't work. I tried changing the default size to 0.1 and multiplying the size by 50000 and also changing the default size to 5000 and setting the value to 0 at times 0-5, yet it only stays the default size.

Then, when super sizing a BlackHole to size 5000, when falling in the pitch is higher than the normal blackhole and normal-sized singularities. would be fun if you could change the volume and pitch of the BlackHole sounds

### What was supposed to happen?

BlackHole curve attribute will multiply the blackhole size by the provided value

BlackHole would have the same deep hum when falling into it when its supersizedit's

### Platform

Steam

### Mods

```Markdown
New Horizons Dev Build
PacificEngine's Common Resources
Cheats Mod
Unity Explorer
Run In Background
Collider Visualizer
```

### Logs

```Shell
Not listed
```

**Comment by xen-42** [comment]
Todo
- [ ] Apply scale curve to singularities
- [ ] Fix pitch shift when changing size
- [ ] Add pitch option
