### ISSUE TITLE
A little more atmosphereShader customizability.

### ISSUE THREAD

**Issue by mrwallace888** [Outer-Wilds-New-Horizons/new-horizons#233]
### Feature

At least the ability to change the color of the sun in the sky when on a planet.

### Context

Thought about making _Rodina_'s Zorica star system in _Outer Wilds_ and on each of the four planets, the Zorica sun in the sky is different colors.

# Jarilo
![image](https://user-images.githubusercontent.com/39398330/179029554-f5a33626-4728-4ba9-908d-3e1a5708572a.png)
![image](https://user-images.githubusercontent.com/39398330/179029528-16d1e790-8801-4ce6-bd08-08b80ceb5aec.png)

# Morena
![image](https://user-images.githubusercontent.com/39398330/179029606-43878282-5d7b-4e96-b50e-4e61ac179333.png)
![image](https://user-images.githubusercontent.com/39398330/179029624-171969d8-d41f-40c9-8432-ba407c507763.png)

# Perun
![image](https://user-images.githubusercontent.com/39398330/179029655-5ef0604e-b12b-4712-a50a-1de6da283b6f.png)
![image](https://user-images.githubusercontent.com/39398330/179029688-f5dc7361-5e08-4f92-b5f0-2a934cd94f7e.png)

# Veles
![image](https://user-images.githubusercontent.com/39398330/179029713-e6f8fc05-8d8a-4087-b8ee-6948f9d8e717.png)
![image](https://user-images.githubusercontent.com/39398330/179029730-1a47101c-5e89-4ff6-8978-57062e851548.png)

**Comment by MegaPiggy** [comment]
Now while this would be nice to have, it is pretty hard to do that with just the Outer Wilds shaders.

**Comment by xen-42** [comment]
Unfortunately we won't be doing this, having that level of atmospheric shader customization is better off being part of the addon itself instead of being in NH
