### ISSUE TITLE
Option to make Stars have no (or less) effect while player is within planet/moon atmosphere

### ISSUE THREAD

**Issue by Onemario1234** [Outer-Wilds-New-Horizons/new-horizons#292]
### Feature

When on the Hourglass Twins, even when the Sun is at its biggest and the Twins are at their closest, you aren't effected by the Sun's gravity as long as you're in the atsmosphere. An option for this effect in planets created using New Horizons would be nice.

### Context

I want to make a Quantum Moon that can orbit the Hourglass Twins, but whenever I land on the Twins variant, the moon's gravity is almost completely overtaken by the sun, making landing nearly impossible.

**Comment by xen-42** [comment]
Can be solved by increasing the priority of the gravity of the moon/planet. Might also have to add a zero g volume with lower priority to cancel out the sun's gravity before applying that of the planet.
