### ISSUE TITLE
Warp drive working wrong with FactRequired

### ISSUE THREAD

**Issue by hearth1an** [Outer-Wilds-New-Horizons/new-horizons#295]
### What Happened?

"canEnterViaWarpDrive": false 
 "factRequiredForWarp": "factID"
 
 with this things revealing the fact needed triggering warp drive dialogue and I still can use warp drive

### What was supposed to happen?

I want to be able to warp only with Vessel in this case

### Mods

```Markdown
New Horizons
```

**Comment by xen-42** [comment]
Fixed in nightly
