### ISSUE TITLE
Beam lights working when reading other text near computer

### ISSUE THREAD

**Issue by hearth1an** [Outer-Wilds-New-Horizons/new-horizons#313]
### What Happened?

I placed nomai recorder near nomai computer and it's working kinda buggy. I'm reading the recorder, but translator beam lights are showing nomai computer ring 

![image](https://user-images.githubusercontent.com/106444732/187076725-637464aa-64c1-4b0b-beaf-454f3adc55e2.png)

### What was supposed to happen?

They should be disabled smh

### Mods

```Markdown
New Horizons
```

**Comment by xen-42** [comment]
I assume this is probably a base game issue, and the solution is just to space out things that can be translated more

**Comment by MegaPiggy** [comment]
Not really. The reason this happens is because our colliders are too big.

**Comment by xen-42** [comment]
This issue isn't wall text tho, it's a recorder and computer

**Comment by xen-42** [comment]
Should open a new feature issue requesting wall text collider to resize to fit the text in it instead and close this as won't do because it's vanilla
