### ISSUE TITLE
Warping to another system prevents putting the suit away.

### ISSUE THREAD

**Issue by mrwallace888** [Outer-Wilds-New-Horizons/new-horizons#333]
### What Happened?

Got a Hearth-like planet you want to explore with your suit off? You can’t put your suit away when you warp to a system.

**Comment by MegaPiggy** [comment]
but you can put away your suit in the ship

**Comment by mrwallace888** [comment]
> but you can put away your suit in the ship

Not if you warp to another system. It only lets me have the pre-flight checklist. This is a known bug.
