### ISSUE TITLE
Volume Shells (or even just Audio Volume Shells)

### ISSUE THREAD

**Issue by mrwallace888** [Outer-Wilds-New-Horizons/new-horizons#334]
### Feature

Allows one to set a minimum radius for volumes or just audio volumes. If you’re inside a volume and you travel closer to the center of it, past a set point it stops working. An example is having a planet with both low altitude and high altitude sounds, but you don’t want both sounds to overlap one another since the volumes are inside each other.

**Comment by JohnCorby** [comment]
you can accomplish this using priority on the audio volumes. for no sound you could just have an audio volume with an empty wav file or something
