### ISSUE TITLE
Texture Painting

### ISSUE THREAD

**Issue by mrwallace888** [Outer-Wilds-New-Horizons/new-horizons#340]
### Feature

Doesn't have to be done but I wanted to create an issue just so it's here, I know John was talking about it at one point when I brought it up.

You'd basically use grayscale mask textures (black being non-existent, gray being faded, white being max-intensity), and in the heightmap schema they'd be assigned to different types of terrain materials (grass, rock, sand, snow, ice, etc. though I guess sand could technically be used for snow too) which would be applied via multiply overlap on the terrain. It would grab the textures for the specified type's albedo/diffuse, normal, specular, and also probably material, and for the albedo it'd grayscale it (as well as brighten up the image so it looks whiter to prevent the terrain from darkening), and apply it in the masked areas for each mask texture.

### Context

```
"Heightmap" :
	{
		"textureMap": "planets/assets/planet one/planet.png",	
		"heightMap": "planets/assets/planet one/planet heightmap.png",	
		"minHeight": 100,
		"maxHeight": 250,
		"resolution": 1024
		"terrainDetail": [
			{
				"path": "planets/assets/planet one/mask 1.png",
				"type": sand,
				"scale": 1.5
			},
			{
				"path": "planets/assets/planet one/mask 2.png",
				"type": rock,
				"scale": 1.5
			},
			{
				"path": "planets/assets/planet one/mask 3.png",
				"type": grass,
				"scale": 1.5
			}
		]
	}
```

**Comment by xen-42** [comment]
I really think we should do this

**Comment by mrwallace888** [comment]
Has this had any progress?

**Comment by MegaPiggy** [comment]
nothing so far

**Comment by xen-42** [comment]
This has been done for a bit now and we forgot about this issue
