### ISSUE TITLE
Allow props to be positioned relative to a parent rather than the center of a body

### ISSUE THREAD

**Issue by artificialparanoia** [Outer-Wilds-New-Horizons/new-horizons#347]
### Feature

Instead of having the xyz positional and rotational coordinates of props be based off of the center of the NH body in the planet config, allow for them to be based off their parent in the scene hierarchy (such as when a parent is manually set with `parentPath`) even if the parent defaults to the root body if not explicitly set. Additionally, allow NH dialogue volumes to be parented and allow for similar functionality for ease of use.

**Comment by MegaPiggy** [comment]
Dialogue volumes can be parented using `pathToAnimController`
