### ISSUE TITLE
No planets/ship log entries are added

### ISSUE THREAD

**Issue by DomiStyle** [Outer-Wilds-New-Horizons/new-horizons#353]
### What Happened?

The main menu will get changed and add the new banner to the DLC area but ingame everything seems to be in a vanilla state, no ship entries or new planets are generated.

Full disclaimer, I'm running this game on Linux with Proton. The issue might be caused by that.

### What was supposed to happen?

Planets should be changed/added and ship log entries should appear.

### Platform

Steam

### Mods

```Markdown
* New Horizons
* Vanilla Fix
* Any New Horizons Mod
```

### Logs

Unfortunately there are no exceptions with any mod except The Vision (issue for that is [here](https://github.com/hearth1an/hearthian.TheVision/issues/29))

Here is a complete verbose log from start to finish with Outer Wilds Galaxy enabled:

https://gist.github.com/DomiStyle/744f307dc52f67883e9d3d3fa1ba26df

Just for completeness, here's the verbose logs with The Vision enabled:

https://gist.github.com/DomiStyle/cc291d5f935e64557825fcd8306a6a2c

**Comment by mrwallace888** [comment]
For the record, you _did_ check the ship computer? You've got the map and rumors, but if you press the rumor mode button on the map, you bring up an interstellar menu which is where you fast travel between systems.

**Comment by DomiStyle** [comment]
Good point, either I can't find the interstellar menu or there is none. This is what the ship computer looks like with New Horizons + Real Solar System enabled on a fresh save:

![20220906124029_1](https://user-images.githubusercontent.com/975131/188616171-80709b9c-59b8-40a9-b903-be70e5cd38ad.jpg)

![20220906124038_1](https://user-images.githubusercontent.com/975131/188616190-3ec1b5fb-0097-475f-a2de-ad6068e157ba.jpg)

Pressing C just toggles between those 2 views.

**Comment by mrwallace888** [comment]
Is there a "MODS" section in the pause menu? Do your mods show up?

What about non-NH mods? Do those work at all?

**Comment by DomiStyle** [comment]
Yes, every mod so far is working except New Horizons.

The mods section is there, the debug menu for New Horizons is there, the main menu gets changed. Just ingame everything looks vanilla.

**Comment by DomiStyle** [comment]
Found the cause.

https://github.com/Outer-Wilds-New-Horizons/new-horizons/blob/main/NewHorizons/Main.cs#L489
https://github.com/Outer-Wilds-New-Horizons/new-horizons/blob/main/NewHorizons/Main.cs#L524

The `?` at the end of the search string causes Mono (in this case) to not find any files, preventing any systems and planets from being loaded.
No idea why, it works in both Mono on Linux and Mono in Wine when testing normally. Maybe something is bugged in the specific version of Mono Outer Wilds uses.

This was added 4 months ago in this commit: https://github.com/Outer-Wilds-New-Horizons/new-horizons/commit/175b8c1f8017fff2e668206a3a04b2acf84486a5

@Bwc9876 Is the JSONC support used anywhere or can I just remove the `?` in a PR? If not I can also try both variants so nothing breaks for current mods.

**Comment by Bwc9876** [comment]
Yes, some of our users use jsonc to allow for comments, we'll just have to change how we load them, thank you for figuring it out!

**Comment by DomiStyle** [comment]
Thanks, will put in a PR later today which looks for both then.

**Comment by DomiStyle** [comment]
Closing this since it's fixed by the PR.
