### ISSUE TITLE
QSB support

### ISSUE THREAD

**Issue by willparsons** [Outer-Wilds-New-Horizons/new-horizons#357]
### Feature

It would be great if this was QSB compatible so we could co-op the vision mod. 

### Context

There's probably a good reason it's not supported but I haven't seen an answer.

**Comment by xen-42** [comment]
we're working on it <https://github.com/Outer-Wilds-New-Horizons/nh-qsb-compatibility>

**Comment by willparsons** [comment]
thanks!

**Comment by willparsons** [comment]
Is there anything that could be helped with?

**Comment by xen-42** [comment]
Most of the issues are on the QSB end, right now it works well enough there's just weird bugs with Epic transport or smthng. You can try asking them about it, either on their repo or the modding Discord server linked on the website https://outerwildsmods.com/

**Comment by JohnCorby** [comment]
closing this as qsb nh support is not feasible anymore
