### ISSUE TITLE
Vision torch targets sometimes don’t activate the first time

### ISSUE THREAD

**Issue by FreezeDriedMangos** [Outer-Wilds-New-Horizons/new-horizons#358]
### What Happened?

This bug applies only to vision torch targets (the kind that you aim a held vision torch at to activate). 

Description: sometimes, the torch will lock on to the target but not start the vision. You have to stop activating the torch and try again to get the vision to start. It always starts on the second attempt

### Platform

Steam

**Comment by JohnCorby** [comment]
appears to have not been an issue since this one time
