### ISSUE TITLE
Rings stop rendering after a certain distance

### ISSUE THREAD

**Issue by Jammer232** [Outer-Wilds-New-Horizons/new-horizons#370]
### What Happened?

When I made a galactic core have a accretion disk around 10x the size of the OW solar system, new horizons stopped rendering it at a certain distance. This is a bug and not a feature, so technically you should fix it.

### Platform

Steam

### Mods

```Markdown
My mod, my mod only, my mod!
```

**Comment by MegaPiggy** [comment]
Mfw you make an accretion disk bigger than the far clip plane smh

**Comment by Jammer232** [comment]
Realism! 

> Mfw you make an accretion disk bigger than the far clip plane smh

**Comment by xen-42** [comment]
We will not fix this, sorry.

**Comment by xen-42** [comment]
Ok we could do this (far clip plane distance setting on system config)

**Comment by mrwallace888** [comment]
> Ok we could do this (far clip plane distance setting on system config)

Will you just force SSAO off or something? You said SSAO breaks when this is modified.

**Comment by xen-42** [comment]
itll just break it, yeah. if you wanna do that then u can do it
