### ISSUE TITLE
Vision Torch Targets fail if the player’s screen resolution is too high

### ISSUE THREAD

**Issue by FreezeDriedMangos** [Outer-Wilds-New-Horizons/new-horizons#381]
### What Happened?

When trying to play a vision using a vision torch target, if the player’s resolution is too high (may depend on the power of their pc), “vision torch target” visions just display a black screen, and still play music. It is unknown what would happen if a vision was allowed to play through to the end in this state.

Watch HelloStudents’ VOD of The Vision to see the bug in action and watch us struggle to debug it in real time.

### What was supposed to happen?

It was supposed to work

### Platform

Steam

### Mods

```Markdown
The Vision
NH and all required dependencies
```

### Logs

```Shell
Nothing out of the ordinary
```

**Comment by MegaPiggy** [comment]
https://www.twitch.tv/videos/1584650357

**Comment by FreezeDriedMangos** [comment]
Likely cause: the black screen is caused by images not being loaded by the time the vision tries to play. Playing on lower res allows the computer to have enough resources available to load the slides on time. We currently do nothing to handle images not being loaded at time of playing. Again this is just a hypothesis.

**Comment by xen-42** [comment]
Removing priority from this bc it happened once and i don't think anyone knows how to recreate it

**Comment by JohnCorby** [comment]
appears to have not been an issue since this one time
