### ISSUE TITLE
Tornados break when rendered at large sizes.

### ISSUE THREAD

**Issue by mrwallace888** [Outer-Wilds-New-Horizons/new-horizons#403]
### What Happened?

My gas giant is 4000 meters in radius and made tornados that are 3700 meters in height (the inner clouds are 3700 meters). After experimenting it appears that large scales for tornados completely bork up the rendering, making them appear almost pitch-black. This effect is dependent on how big or small the tornado is. At 500 meters they appear to get a little blacker but not as much as it does at 3700 meters.
![image](https://user-images.githubusercontent.com/39398330/192869531-8616bae3-0cd0-4239-a763-bce66c1e2137.png)

For reference, these tornados are given a tint of 255, 255, 255, 255.

### Platform

Steam

**Comment by xen-42** [comment]
Does this happen when they are not tinted?

**Comment by JohnCorby** [comment]
just dont make big tornado LOL
