### ISSUE TITLE
Raycast outputting object path

### ISSUE THREAD

**Issue by FunkyShoeMan** [Outer-Wilds-New-Horizons/new-horizons#423]
### Feature

The raycast currently gives the position and normal of whatever spot you hit, but what if hitting something with a raycast also gave you the object's name and it's path?

### Context

![Screenshot_20221017-104449](https://user-images.githubusercontent.com/111538779/196208061-4132cf80-827c-4534-992f-4276b1312c0d.png)

**Comment by dgarroDC** [comment]
Implemented in 15c73d3339ba0e0440e47cd805245a3215a97492
