### ISSUE TITLE
Making any ship log mistakes breaks computer

### ISSUE THREAD

**Issue by xen-42** [Outer-Wilds-New-Horizons/new-horizons#46]
Ideally we would catch these errors. One I've noticed is that if it can't find the source ID for a rumour everything breaks. We should have it default the source to something it knows exists. There are probably more.

**Comment by JohnCorby** [comment]
skill issue

**Comment by xen-42** [comment]
skill issue

we don't validate anything else, somebody can make an xml editor for ship logs if they really want this to work better
