### ISSUE TITLE
Better NH characters

### ISSUE THREAD

**Issue by artificialparanoia** [Outer-Wilds-New-Horizons/new-horizons#469]
### Feature

It would be nice if NH could support slightly more complex functionality that mimics some of the behavior in the base game, such as some characters turning their bodies to face you or traveler's stopping their playing animations and music when spoken to. At least a rudimentary system to control some character behavior through NH and not code would be nice, as editing existing characters can be very broken otherwise.

**Comment by xen-42** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
