### ISSUE TITLE
Signals are not restarting on pause

### ISSUE THREAD

**Issue by hearth1an** [Outer-Wilds-New-Horizons/new-horizons#479]
### What Happened?

Signals created with NH are not playing from start after pause

### What was supposed to happen?

Travellers signals are restearting after the pause and playing from beginning.

### Platform

None

**Comment by MegaPiggy** [comment]
I'm not sure what this means

**Comment by JohnCorby** [comment]
im testing christmas mod now, and signals are indeed playing from the start after pausing and unpausing. so im counting this as fixed
