### ISSUE TITLE
NH disabling/enabling existing objects on condition/fact revealed

### ISSUE THREAD

**Issue by hearth1an** [Outer-Wilds-New-Horizons/new-horizons#482]
### Feature

Would be nice to have an ability to load disabled props on start or make existing game objects not load on start. This may be useful for story mods especially like when you need to replace any characters dialogue or just replace the characters themselfs without any code. This will give a possibility to control such things with dialogues, facts, texts etc etc.

here's how it could look like

"vanillaGameObjects": 
[{
"path": string
"disabledOnStart": bool,
"revealOnCondition": string,
"revealOnPersistentCondition": string,
"disableOnCondition": string,
"disableOnPersistentCondition": string,
"revealOnFactReveal": string,
"disableOnFactReveal": string
}]

**Comment by xen-42** [comment]
Disabling objects on start already exists (see `removeChildren`) the other options are a bit too particular and aren't really features in the base game. We could leave this as a wishlist thing.

**Comment by hearth1an** [comment]
alrigh, then enabling/revealing things with conditions would be cool
