### ISSUE TITLE
Crashes when Leaving Home System

### ISSUE THREAD

**Issue by SoulfireStudio** [Outer-Wilds-New-Horizons/new-horizons#490]
### What Happened?

Every time I go to leave the home system, and more recently, upon loading my save, my game crashes. My OWML logs tell me it's a memory issue. The error is

> Could not allocate memory: System out of memory!
Trying to allocate: 11184816B with 16 alignment. MemoryLabel: Texture
Allocation happened at: Line:78 in
Memory overview
[ ALLOC_TEMP_THREAD ] used: 32768B | peak: 0B | reserved: 6225920B
[ ALLOC_TEMP_JOB_1_FRAME ] used: 0B | peak: 0B | reserved: 6291456B
[ ALLOC_TEMP_JOB_2_FRAMES ] used: 0B | peak: 0B | reserved: 1048576B
[ ALLOC_TEMP_JOB_4_FRAMES ] used: 2496851B | peak: 0B | reserved: 127926272B
[ ALLOC_TEMP_JOB_ASYNC ] used: 0B | peak: 0B | reserved: 22020096B
[ ALLOC_DEFAULT ] used: 909993068B | peak: 0B | reserved: 932630528B
[ ALLOC_GFX ] used: 681040380B | peak: 0B | reserved: 694517760B
[ ALLOC_CACHEOBJECTS ] used: 589420784B | peak: 0B | reserved: 662876160B
[ ALLOC_TYPETREE ] used: 1002496B | peak: 0B | reserved: 5242880B

I'm not sure what to do at this point...

### What was supposed to happen?

I would assume what should have happened is that I should have warped to the selected star system.

### Platform

Steam

### Mods

```Markdown
Mod list was as follows:
OWMM
OWML
New Horizons
Menu Framework
Vanilla Fix
Clock
Common Camera Utility
Real Solar System
ScoutStreaming
Custom Ship Log Modes
New Horizons Examples
Voice Acting Mod
Achievements+
Funny System
Quality of Life Changes
Cut Achievements
Ship Remote Autopilot
```

### Logs

```Shell
I said it above, but here's the error again:

Could not allocate memory: System out of memory!
Trying to allocate: 11184816B with 16 alignment. MemoryLabel: Texture
Allocation happened at: Line:78 in
Memory overview
[ ALLOC_TEMP_THREAD ] used: 32768B | peak: 0B | reserved: 6225920B
[ ALLOC_TEMP_JOB_1_FRAME ] used: 0B | peak: 0B | reserved: 6291456B
[ ALLOC_TEMP_JOB_2_FRAMES ] used: 0B | peak: 0B | reserved: 1048576B
[ ALLOC_TEMP_JOB_4_FRAMES ] used: 2496851B | peak: 0B | reserved: 127926272B
[ ALLOC_TEMP_JOB_ASYNC ] used: 0B | peak: 0B | reserved: 22020096B
[ ALLOC_DEFAULT ] used: 909993068B | peak: 0B | reserved: 932630528B
[ ALLOC_GFX ] used: 681040380B | peak: 0B | reserved: 694517760B
[ ALLOC_CACHEOBJECTS ] used: 589420784B | peak: 0B | reserved: 662876160B
[ ALLOC_TYPETREE ] used: 1002496B | peak: 0B | reserved: 5242880B
```

**Comment by SoulfireStudio** [comment]
I just tried removing the Funny Systems addon and it still crashed upon loading. Before adding New Horizons Examples, it would only crash upon leaving the home system. or more precisely, I think it always crashes upon attempting to load a non-vanilla system. I would assume NH Examples loads you straight into the examples system, causing my game to crash upon attempting to load it.

**Comment by SoulfireStudio** [comment]
wrong button didnt mean to close it. I was trying to post a comment with some updates to the situation. After removing the Funny Systems mod and the game still crashing when loading my save, I suspect the NH Examples mod is to blame. Does it spawn you right into the examples? I think loading any modded system is what causes my crash. I will remove NH Examples and test this hypothesis

**Comment by SoulfireStudio** [comment]
> wrong button didnt mean to close it. I was trying to post a comment with some updates to the situation. After removing the Funny Systems mod and the game still crashing when loading my save, I suspect the NH Examples mod is to blame. Does it spawn you right into the examples? I think loading any modded system is what causes my crash. I will remove NH Examples and test this hypothesis

Hypothesis confirmed. The game launches fine now without NH Examples. Warping to a new system, however, has once again crashed my game.

**Comment by SoulfireStudio** [comment]
I wasn't sure if it meant RAM or disk space when it said memory, so after moving the game installation to a drive with more space, it still doesn't work, so I assume it's RAM. Is there a minimum requirement somewhere I don't meet that I'm missing here?

**Comment by MegaPiggy** [comment]
How much RAM and disk space do you have?

**Comment by SoulfireStudio** [comment]
> How much RAM do you have? and how much disk space do you have left?

I've got 32 gigs of ram, and 1.6 terabytes left in the drive

**Comment by SoulfireStudio** [comment]
A recent update has fixed my issue. Thanks to whoever figured out the error and fixed it, I guess!
