### ISSUE TITLE
Scale bramble node/seed fog properly

### ISSUE THREAD

**Issue by xen-42** [Outer-Wilds-New-Horizons/new-horizons#513]
### What Happened?

Do what clay says to do in BramblePatches.cs

        //
        // this file is not great. the real solution to the issues these patches address should be solved by replacing bramble nodes' InnerFogWarpVolume
        // components with a custom NHInnerFogWarpVolume component, and implement the below functions as overrides in the NHInnerFogWarpVolume class
        // that would fix the issue of seeds having inappropriate screen fog
        //

### Platform

None

**Comment by JohnCorby** [comment]
a better solution would be to just make it so that it scales properly (as in, with default scale the value is 50, so like 50 * config.scale rather than just _exitRadius)
