### ISSUE TITLE
Change default image for discovered ship log entries

### ISSUE THREAD

**Issue by Acamaeda** [Outer-Wilds-New-Horizons/new-horizons#518]
### Feature

Right now the default image for discovered ship log entries is the same as for undiscovered entries, so you can't tell if it's been discovered or not. Changing it to a check mark or something would help a lot both for developing and playing mods.

**Comment by Bwc9876** [comment]
This would be a bit difficult to do since we set images at build time, and can't really change them.

**Comment by Bwc9876** [comment]
This already happens, when an entry is rumored it shows as a question mark (1) and when it's discovered it's a "No Photo" picture (2)

![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/25644444/e846f6de-5830-4b84-ae49-5b922df3d924)
![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/25644444/e75cc181-b9ca-4a87-9a84-c1e9f5d1eb05)
