### ISSUE TITLE
Make asteroids take a planet config

### ISSUE THREAD

**Issue by xen-42** [Outer-Wilds-New-Horizons/new-horizons#521]
### Feature

Allow asteroids to take a list of planet configs, and then it will use those as prefabs to make however many asteroids you want. Will allow people to make asteroids with unity detailing

**Comment by Bwc9876** [comment]
This could create an issue with schema generation as I don't know if it can handle recursive data structures like that.

**Comment by xen-42** [comment]
I intended it to be entire configs in the asteroid module tbh

**Comment by xen-42** [comment]
Nobody wants this, just make a billion configs if you care
