### ISSUE TITLE
i need fog sphere

### ISSUE THREAD

**Issue by ClassicalBro** [Outer-Wilds-New-Horizons/new-horizons#530]
### Feature

it'd be cool i swear, even though im the only one that noticed this in 1 year

timber hearth has a special fog sphere that makes it blue on the front

### Context

![fact](https://user-images.githubusercontent.com/51799477/221392746-29af1633-b3f3-4e26-b96e-cbf9e281cf09.png)
![i need](https://user-images.githubusercontent.com/51799477/221392809-843e4001-9e34-4af0-9963-4e7614abf6ec.png)

**Comment by JohnCorby** [comment]
should be pretty easy? just expose the fogramp property
