### ISSUE TITLE
Blackbody Radiation Colors for stars

### ISSUE THREAD

**Issue by FunkyShoeMan** [Outer-Wilds-New-Horizons/new-horizons#531]
### Feature

Let users put in the Kelvin Teampture for the color of stars instead of a RGBA 0-255

### Context

 i want to be able to make my betufal Trappist-1 star have it's correct color (2,550k) but i can only be silly with the rgb for so long

**Comment by xen-42** [comment]
Would be too complicated. Just use an HR diagram.

![image](https://user-images.githubusercontent.com/22628069/222860837-9ef2ba5b-576e-407f-8ab5-be6da4037f9e.png)

**Comment by xen-42** [comment]
Meant to close as not planned

**Comment by FunkyShoeMan** [comment]
i am going to kill you with a rock!!!

**Comment by MegaPiggy** [comment]
ok arkose
