### ISSUE TITLE
Heightmap sphere collider breaks when stretched

### ISSUE THREAD

**Issue by TerrificTrifid** [Outer-Wilds-New-Horizons/new-horizons#551]
### What Happened?

When using heightmap stretch, the sphere collider scales to the highest stretch value instead of the lowest, causing it to be way above the terrain.

### What was supposed to happen?

It should just scale to the lowest value.

### Platform

None

**Comment by JohnCorby** [comment]
this is default unity behavior when you scale an object with a SphereCollider on it. to fix it, we should put the spherecollider on a child and then explicitly set the scale of that to be min(scale x, scale y, scale z)
