### ISSUE TITLE
"None" vine prefab causes NRE on dimension enter

### ISSUE THREAD

**Issue by coderCleric** [Outer-Wilds-New-Horizons/new-horizons#562]
### What Happened?

When I entered a dimension that I had set to have the "none" vine prefab, I got an NRE. This caused the bramble dimension to not properly load in, leaving me drifting in empty fog. 
I checked using the "cluster" prefab and that one worked fine, so I think it's specifically a problem with having no vines.

### What was supposed to happen?

I should have entered the dimension without vines, with it loading properly.

### Platform

Steam

### Mods

```Markdown
NH and its dependencies, Nomai Text Printer, and my custom addon.
```

### Logs

```Shell
NullReferenceException
Stacktrace: NewHorizons.Components.BrambleSectorController.EnableRenderers () (at <af3dbe99d59e4e0eacbeb75214ec8b8d>:0)
NewHorizons.Components.BrambleSectorController.OnSectorOccupantsUpdated () (at <af3dbe99d59e4e0eacbeb75214ec8b8d>:0)
OWEvent.Invoke () (at <8585b6cb325949f692883e4747187a22>:0)
UnityEngine.Debug:LogException(Exception)
OWEvent:Invoke()
Sector:AddOccupant(SectorDetector)
Sector:OnEntry(GameObject)
OWTriggerVolume:FireEntryEvent(GameObject)
OWTriggerVolume:AddObjectToVolume(GameObject)
FogWarpVolume:DMD<FogWarpVolume::ReceiveWarpedDetector>(FogWarpVolume, FogWarpDetector, Vector3, Vector3, Quaternion)
FogWarpVolume:DMD<FogWarpVolume::WarpDetector>(FogWarpVolume, FogWarpDetector, FogWarpVolume)
SphericalFogWarpVolume:CheckWarpProximity(FogWarpDetector)
InnerFogWarpVolume:CheckWarpProximity(FogWarpDetector)
FogWarpDetector:FixedUpdate()
```

**Comment by JohnCorby** [comment]
clearly there's a null renderer somewhere but im not sure how BrambleSectorController coulda picked up the renderer before it was destroyed given we do the vine none stuff before adding BrambleSectorController

**Comment by coderCleric** [comment]
I'm not sure if it's helpful, but it was actually working before the 1.10.0 update.

**Comment by JohnCorby** [comment]
thats probably related to [this fix](https://github.com/Outer-Wilds-New-Horizons/new-horizons/commit/36a31f3b807f327625687eceebde6a0a44af7f4f) then
