### ISSUE TITLE
Clouds do not swirl

### ISSUE THREAD

**Issue by snazzyostrich** [Outer-Wilds-New-Horizons/new-horizons#571]
### What Happened?

i set the clouds prefab on this object to giantsDeep, yet it stays the same as how it is in the cloud texture
![Screenshot 2023-04-05 133317](https://user-images.githubusercontent.com/95659988/230159431-e303cecf-b556-49ce-b99c-757179d163b3.png)

### What was supposed to happen?

the clouds swirl

### Platform

None

### Mods

```Markdown
menu framework
vanilla fix
custom ship log modes
voice acting mod
cheat and debug menu
suit log
discord rich presence
timesaver
trajectory prediction
altertime
hug mod
```

### Logs

```Shell
there are no nh errors for some reason and there are warnings but none of them contain "venus"
```

**Comment by xen-42** [comment]
can you share the config file please

**Comment by xen-42** [comment]
Could not reproduce
