### ISSUE TITLE
Automatically Reset/Clear signalscope signals/frequencies from uninstalled addons

### ISSUE THREAD

**Issue by QuantumBlur314** [Outer-Wilds-New-Horizons/new-horizons#572]
### Feature

Addon-unique Signalscope signals & frequencies haunt profiles after their respective addons have been uninstalled.  probably fix maybe?  yes i know about save.json

**Comment by xen-42** [comment]
What does "yes i know about save.json" mean?

**Comment by JohnCorby** [comment]
it means he knows about deleting save.json to remove the signals and frequencies but does not want to do that
