### ISSUE TITLE
Remove unnecessary Destroys

### ISSUE THREAD

**Issue by JohnCorby** [Outer-Wilds-New-Horizons/new-horizons#573]
Around the codebase (but mainly in [here](https://github.com/Outer-Wilds-New-Horizons/new-horizons/blob/main/NewHorizons/Handlers/PlanetDestructionHandler.cs)) we do calls to Destroy when we probably could just be doing SetActive(false)

It would be easier/nicer if we were more consistent with this. Obviously testing required.

**Comment by JohnCorby** [comment]
it would also fix the "what." bug presumably wouldnt happen since ForceVolumes wouldnt be destroyed ("what" is caused by a null ForceVolume in ForceDetector, and the only way for that to happen is if the volume was destroyed)

**Comment by FreezeDriedMangos** [comment]
I tested removing the destroy call in `PlanetDestructionHandler.DisableBody` with my current build of Uncertain Futures, in a system that is empty apart from one planet without a surface (and that has one prop loaded from an asset bundle). 

No issues were found during this test.

For reference, I simply commented out some of the lines at the end of the function:
```
            //if (delete)
            //{
            //    GameObject.Destroy(go);
            //}
            //else
            //{
                go.SetActive(false);
                var ol = go.GetComponentInChildren<OrbitLine>();
                if (ol)
                {
                    ol.enabled = false;
                }
            //}
```

**Comment by JohnCorby** [comment]
me i will test this at some point with some mods one day eventually and then see if it explodes

**Comment by JohnCorby** [comment]
according to #670 this apparently breaks shit or something idk

**Comment by xen-42** [comment]
@JohnCorby its because that PR patched the destroy method so that nothing ever can be destroyed either by base game or by other mods. Doesn't necessarily mean that stopping our code destroying stuff would be bad.
