### ISSUE TITLE
RAM and VRAM usage

### ISSUE THREAD

**Issue by JohnCorby** [Outer-Wilds-New-Horizons/new-horizons#578]
some addons are beginning to get to a point where they cannot be played by some people because of vram usage.
we may have to finally start looking into this.

particularly, for RSS
- check heightmap texture usage - how does 100 mb cause multiple gb of ram/vram usage?
- can we Destroy base game textures/meshes to free of memory? can we do this in a way that doesnt mess up details?
- can we upload textures/meshes to be GPU-only? can we do this in a way that doesnt break things that edit the texture on the CPU, like invert? this wouldnt save VRAM but it would save RAM

**Comment by Bwc9876** [comment]
Could implement a build pattern that takes closures to apply to a texture and only actually performs said closures on a `Finalize` method or smth

**Comment by xen-42** [comment]
Adding on to what Idiot said. Say you create a NHTexture object, then on that you call a LoadFile method, Tint method, Invert method, etc. Then at the end when you try to access the actual texture from it, it will try to look up that image in the file cache and if its not there only then will it load the file and apply the effects to it. This class could also be in charge of deleting the intermediate textures and just keeping the final texture.

**Comment by TextureTurtle** [comment]
Moving all of Outer Wilds to utilize RAM and VRAM entirely would significantly enhance performance and alleviate existing issues. By leveraging the full potential of these resources, the game's data and assets could be accessed and processed more efficiently, resulting in faster loading times, smoother gameplay, and reduced latency. The decreased memory capacity and bandwidth offered by RAM and VRAM would allow for seamless rendering of complex environments, intricate physics simulations, and detailed textures, resulting in a more immersive and visually stunning experience. This optimization would not only address performance concerns but also unlock new possibilities for the game's mechanics, enabling NH mod creators to push the boundaries of exploration and interactivity even further.

**Comment by MegaPiggy** [comment]
> Moving all of Outer Wilds to utilize RAM and VRAM entirely would significantly enhance performance and alleviate existing issues. By leveraging the full potential of these resources, the game's data and assets could be accessed and processed more efficiently, resulting in faster loading times, smoother gameplay, and reduced latency. The decreased memory capacity and bandwidth offered by RAM and VRAM would allow for seamless rendering of complex environments, intricate physics simulations, and detailed textures, resulting in a more immersive and visually stunning experience. This optimization would not only address performance concerns but also unlock new possibilities for the game's mechanics, enabling NH mod creators to push the boundaries of exploration and interactivity even further.

big brain

**Comment by xen-42** [comment]
turtle is banned now

**Comment by JohnCorby** [comment]
turns out that texture duplication isnt actually that big of an issue, i think. need to test texture cache misses and hits to see if the cache is actually important etc.

i think the biggest deal will be just legit doing everything on the GPU and then only keeping textures on the CPU is absolutely needed (like heightmaps). this will be very painful.

could use command buffers to make a single draw wtv idk anything.
also compute shaders this will suck.
testing will kill me

**Comment by JohnCorby** [comment]
clearly the best solution as addon dev is just do everything in unity since it seems to actually compress guy and load faster and just be better in general

**Comment by xen-42** [comment]
Just use unity
