### ISSUE TITLE
I frames upon spawning

### ISSUE THREAD

**Issue by TextureTurtle** [Outer-Wilds-New-Horizons/new-horizons#587]
### Feature

Give the player I-frames when they spawn to fix possible spontaneous death

### Context

And have I not told you that what you mistake for madness is but over-acuteness of the sense? --now, I say, there came to my ears a low, dull, quick sound, such as a watch makes when enveloped in cotton. I knew that sound well, too. It was the beating of the old man's heart. It increased my fury, as the beating of a drum stimulates the soldier into courage. 
![istockphoto-1041299888-612x612](https://user-images.githubusercontent.com/16947391/236691410-c01d8ec4-c262-4152-aa53-a2a1dc63fa37.jpg)

**Comment by JohnCorby** [comment]
you should probably figure out why ur spontaneously dying on spawn before trying to hack around it with i-frames. if you really need them, just do it with code (blehh)

**Comment by JohnCorby** [comment]
maybe make an issue for that if u figure out why
