### ISSUE TITLE
Water buoyancy

### ISSUE THREAD

**Issue by drjames5** [Outer-Wilds-New-Horizons/new-horizons#594]
### Feature

Water in new horizons is very...light. You usually don't stop sinking until your well underwater. It would be nice to have a setting that could bring the water to a buoyancy comparable to say giants deep and maybe beyond. Would allow for a realistic approach to non-water oceans and lakes.

**Comment by MegaPiggy** [comment]
I'm pretty sure this is already a thing considering I was the one who added it.

buoyancy is in the water module
https://github.com/Outer-Wilds-New-Horizons/new-horizons/blob/0e0f3452452412bb73d1153cffa69772c8136e77/NewHorizons/External/Modules/VariableSize/WaterModule.cs#L15-L23

**Comment by drjames5** [comment]
oh
im stupid
