### ISSUE TITLE
Customizable gravity fields

### ISSUE THREAD

**Issue by drjames5** [Outer-Wilds-New-Horizons/new-horizons#595]
### Feature

A gravity field that is not just a singularity, but rather say a short line would be nice. A planet which is elongated by one axis could benefit from this. At the same time, this would also allow for some funky orbits like those around elongated stars.

Of course, this probably wouldn't be code able.

**Comment by JohnCorby** [comment]
this is much easier expressed than accomplished

**Comment by xen-42** [comment]
Won't be doing this since it doesn't reflect the vanilla outer wilds experience. Neat idea though
