### ISSUE TITLE
Fix the what bug

### ISSUE THREAD

**Issue by xen-42** [Outer-Wilds-New-Horizons/new-horizons#596]
### What Happened?

Think this is when constant force detectors have their constant force volume destroyed or set to null and they just NRE on every update call forever after that

We can just patch this to disable them when this happens instead

see [this comment](https://github.com/Outer-Wilds-New-Horizons/new-horizons/issues/573#issuecomment-1506264939)

### Platform

None

**Comment by JohnCorby** [comment]
see [this comment](https://github.com/Outer-Wilds-New-Horizons/new-horizons/issues/573#issuecomment-1506264939)

**Comment by xen-42** [comment]
Duplicate of #573
