### ISSUE TITLE
Quantum states aren't locked by photos

### ISSUE THREAD

**Issue by bruvin-sky** [Outer-Wilds-New-Horizons/new-horizons#598]
### What Happened?

They are defying lore-accurate physics and therefore not god-honoring

### What was supposed to happen?

Be locked into that state while observed by photo

### Platform

None

**Comment by xen-42** [comment]
@bruvin-sky can you provide an example config where this happened

**Comment by FreezeDriedMangos** [comment]
fixed for next release
