### ISSUE TITLE
Warping to a system breaks player fluid detector

### ISSUE THREAD

**Issue by JohnCorby** [Outer-Wilds-New-Horizons/new-horizons#601]
when you warp to any system, the fluid detector seems to not work. the probe doesnt do underwater sounds, audio isnt properly muffled, and probably other things are broken too.

dying after warping fixes the issue

repro: warp to any system. go inside water. it wont muffle sounds

**Comment by xen-42** [comment]
What do you mean dying after warping fixes it. Dying and respawning in that same system? Or dying and respawning on TH

**Comment by JohnCorby** [comment]
i only tested the former

**Comment by xen-42** [comment]
can you test it again in the `custom-spawn-points` branch

**Comment by xen-42** [comment]
This should be fixed now

**Comment by xen-42** [comment]
Just tested, this is fixed for me at least
