### ISSUE TITLE
"track" option on Audio Volumes doesn't properly set track

### ISSUE THREAD

**Issue by 2walker2** [Outer-Wilds-New-Horizons/new-horizons#602]
### What Happened?

I have an audio volume with the track set to "music". In game, the volume of the track is controlled by the "SFX Volume" option instead of the "Music Volume" option.

Investigating the Audio Volume using Unity Explorer shows that the track is set to "environment".

The Volumes section of my config file is:
"Volumes": {
		"audioVolumes": [
			{
				"audio": "planets/assets/probes.mp3",
				"clipSelection": "random",
				"track": "music",
				"position": {
					"x": -32.50764,
					"y": -93.72656,
					"z": -117.636772
				},
				"radius": 50.0
			}
		],
		"oxygenVolumes": [
			{
				"treeVolume": true,
				"position": {
					"x": -20.72586,
					"y": -87.05078,
					"z": -116.832016
				},
				"radius": 25.0
			}
		],
		"revealVolumes": [
			{
				"revealOn": "enter",
				"revealFor": "both",
				"reveals": [
					"codex_ember_memorial",
					"codex_ember_signal_rumor"
				],
				"position": {
					"x": -20.72586,
					"y": -87.05078,
					"z": -116.832016
				},
				"radius": 15.0
			}
		]
	}

### What was supposed to happen?

The track's volume should be controlled by the "Music Volume" option.

### Platform

Steam

### Mods

```Markdown
Outer Wilds Mod Manager
OWML
New Horizons
Vanilla Fix
Menu Framework
Common Camera Utility
Custom Ship Log Modes
Suit Log
Time Saver
Unity Explorer
Developer Console
Console Cheats
Astral Codex
```

### Logs

```Shell
No error generated
```

**Comment by JohnCorby** [comment]
already fixed in #599
