### ISSUE TITLE
Reset and/or change time when entering a new system via black hole or warp.

### ISSUE THREAD

**Issue by drjames5** [Outer-Wilds-New-Horizons/new-horizons#611]
### Feature

Let's say I am [hypothetically] making a quirky little mod and I [hypothetically] want the player to enter a black hole, get teleported to a new scene and then [hypothetically] die after 5 seconds. Because I don't know how to code [hypothetically], I make a star that crashes into the player after 5 seconds. The best way to do this is to time the orbit of the star with the player. But that breaks if the player enters the black hole at the wrong time. Resetting time or at least the starting orbits of the star would fix this.

Besides, I'm pretty sure a cheat mod did this once.

**Comment by xen-42** [comment]
Set `enableTimeLoop` = false in the system config.
