### ISSUE TITLE
Solar Flare colors broken

### ISSUE THREAD

**Issue by GameWyrm** [Outer-Wilds-New-Horizons/new-horizons#616]
### What Happened?

On a custom sun, the solar flares use the default orange even though my sun is supposed to be blue.
Sun schema:
`{
    "$schema": "https://raw.githubusercontent.com/Outer-Wilds-New-Horizons/new-horizons/main/NewHorizons/Schemas/body_schema.json",
    "name": "Jam Sun",
    "starSystem": "GameWyrm.JamSystem",
    "Base": {
        "centerOfSolarSystem": true,
        "gravityFallOff": "inverseSquared",
        "surfaceSize": 2000,
        "surfaceGravity": 500
    },
    "canShowOnTitle": false,
    "Star": {
        "hasAtmosphere": true,
        "lightTint": {
            "r": 220,
            "g": 220,
            "b": 255,
            "a": 255
        },
        "tint": {
            "r": 150,
            "g": 150,
            "b": 255,
            "a": 255
        },
        "endTint": {
            "r": 0,
            "g": 0,
            "b": 255,
            "a": 255
        }
    }
}`
![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/78181444/097ea25c-fcf8-4be7-9b42-2c2c967eacf2)

### What was supposed to happen?

Flares should roughly be the color of the sun's surface

### Platform

Steam

### Mods

```Markdown
OWML
New Horizons
Vanilla Fix
Menu Framework
Common Camera Utility
Custom Ship Log Modes
Cheat and Debug Menu
Unity Explorer
```

**Comment by misternebula** [comment]
the reason for this is that SunController is using it's _solarFlareTint gradient to keep changing the tint/color back to the vanilla sun color

**Comment by xen-42** [comment]
The issue was actually that we were trying to change the colour of existing SolarFlareControllers when creating the star, however they were being made later from prefabs on the SolarFlareEmitter. So we had to change those instead.
