### ISSUE TITLE
Quicktest Mode

### ISSUE THREAD

**Issue by GameWyrm** [Outer-Wilds-New-Horizons/new-horizons#636]
### Feature

Sometimes you want to just quickly jump in and test things, without pesky save data getting in the way. With Quicktest Mode on (as an option in the config menu), as soon as the game boots up, the game will create a new dummy profile and load it, with whatever system you have set as default. You can set the starting loop number in the config as well, with any loop above 0 starting you with the launch codes. You can also engage Quicktest with a new button in the main menu which appears while you have dev mode on, which will not affect the selected profile's save data.

**Comment by JohnCorby** [comment]
from your description, this doesnt seem to actually require nh at all (given it just uses whatever default system u have in ur config). therefore, i think this is better suited as a standalone mod.
