### ISSUE TITLE
Scaled bramble nodes looks too shiny with proxy model

### ISSUE THREAD

**Issue by hearth1an** [Outer-Wilds-New-Horizons/new-horizons#641]
### What Happened?

![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/106444732/ef16c965-721d-48e2-a6ff-c69c9e57661e)

### What was supposed to happen?

It looks okay when getting closer

### Platform

None

### Mods

```Markdown
Origins
```

**Comment by xen-42** [comment]
@hearth1an how far away from it are you when it happens? Could you also provide images of what it is supposed to look like

**Comment by hearth1an** [comment]
I can see this from TH.
![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/106444732/07b7d33c-306c-41ae-a45b-e7d83014f3f6)

**Comment by hearth1an** [comment]
That's how it looks when I'm getting closer 
![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/106444732/ef72e2d1-cd3a-430b-b374-163b67726706)

**Comment by hearth1an** [comment]
Here's the object I can disable to make it look nice again
![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/106444732/9aabbfca-be89-426e-885c-6d231bb1dee0)

**Comment by hearth1an** [comment]
but then DB looks goofy with no fog sphere
![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/106444732/ad779f24-2cc4-4605-999c-f5c3541c6fb3)

**Comment by xen-42** [comment]
when does this happen in your mod? I just loaded in with it and there was nothing

**Comment by hearth1an** [comment]
It's active once you learn the frequency from quantum moon

**Comment by JohnCorby** [comment]
didnt you fix this in the Origins update? how?

**Comment by hearth1an** [comment]
well if disabling the lod at all counts as fix so yeah

**Comment by JohnCorby** [comment]
oh.

**Comment by JohnCorby** [comment]
qskill issue

**Comment by xen-42** [comment]
Assigning to clay because he made bramble nodes

**Comment by xen-42** [comment]
Mfw this was a duplicate of #372 so it's fixed in dev now.
