### ISSUE TITLE
Audivolume not overriding DB music in ship

### ISSUE THREAD

**Issue by hearth1an** [Outer-Wilds-New-Horizons/new-horizons#651]
### What Happened?

When inside the ship you can hear DB classic music and music from audioVolumes. I tried to make it priority 1 and 3. Same problem. 

### Platform

None

### Mods

```Markdown
Origins, in the Enterance dimension (the first one with escape pod, when you enter to the blue bramble)
```

**Comment by JohnCorby** [comment]
this is due to goofy hardcoded guy in GlobalMusicController
![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/26337121/0f55f7bc-3696-493c-9888-04823473214d)
gah
