### ISSUE TITLE
Disable map view inside cloaking field

### ISSUE THREAD

**Issue by SushiRoll55** [Outer-Wilds-New-Horizons/new-horizons#672]
### Feature

Would be nice if under the "Cloak" field in the celestial body schema there was an option to restrict opening the solar system map. Would work just how it does in the th̸̩́e ̴̥̌st̶̠̎ř̷̞anger, where it gives the player that "Unable to pinpoint location" notif.

**Comment by MegaPiggy** [comment]
Just add a map restriction volume

**Comment by SushiRoll55** [comment]
my fault thanks babe
