### ISSUE TITLE
Scale-over-time atmosphere size, color and clouds

### ISSUE THREAD

**Issue by drjames5** [Outer-Wilds-New-Horizons/new-horizons#674]
### Feature

Let's say that I, in a moment of realism, decide I wanna make the atmosphere color change to a redder one as time goes by to simulate the expanding sun burning it away. It would be nice if that was added. Also changing the atmosphere size itself, along with cloud height [The colour of the clouds too].

**Comment by xen-42** [comment]
Colour wouldn't work I don't think because it's done with coloured textures.
Resizing atmosphere is possible at least

**Comment by xen-42** [comment]
NH is done and this isn't a base game feature so no sorry
