### ISSUE TITLE
Ship Spawn doesn't work in main system / without player spawn / when not marked default

### ISSUE THREAD

**Issue by gpixl** [Outer-Wilds-New-Horizons/new-horizons#677]
### What Happened?

The last time I tested my mod, the shipSpawn parameter (used in the main system) spawned my ship in the correct location, and in this version, it doesn't work anymore
I'm only using the shipSpawn, not the playerSpawn!

Here's the entire config (everything else on the planet works as intended, the planet isn't missing)
{
	"$schema": "https://raw.githubusercontent.com/xen-42/outer-wilds-new-horizons/main/NewHorizons/Schemas/body_schema.json",
	"name": "Frosted Grotto",
	"canShowOnTitle": false,
	"Volumes": {
		"audioVolumes": [
			{
				"audio": "planets/Assets/snowy_ambience.ogg",
				"radius": 350.0,
				"track": "muffleIndoors",
				"position": {}
			}
		]	
	},
	"AmbientLights": [
		{
			"intensity": 0.2,
			"tint": {
				"r": 255,
				"g": 255,
				"b": 255,
				"a": 0
			}
		},
	],
	"Atmosphere": {
		"atmosphereTint": {
			"r": 83,
			"g": 66,
			"b": 85,
			"a": 100
		},
		"fogDensity": 0.15,
		"fogSize": 130.0,
		"fogTint": {
			"r": 192,
			"g": 145,
			"b": 201,
			"a": 255
		},
		"hasOxygen": true,
		"hasSnow": true,
		"size": 350.0,
		"useAtmosphereShader": true,
		"hasAtmosphere": true
	},
	"Base": {
		"gravityFallOff": "linear",
		"hasMapMarker": true,
		"surfaceGravity": 10.0,
		"surfaceSize": 250.0
	},
	"Orbit": {
		"primaryBody": "Far Light",
		"siderealPeriod": 3.0,
		"semiMajorAxis": 6000.0
	},
	"Props": {
		"details": [
			{
				"assetBundle": "planets/Assets/snowplanet",
				"path": "Assets/Examples/SnowPlanet.prefab",
				"keepLoaded": true,
				"rotation": {},
				"alignRadial": false,
				"position": {}
			},
			{
				"assetBundle": "planets/Assets/train",
				"path": "Assets/Examples/Train.prefab",
				"scale": 1.00000036,
				"keepLoaded": true,
				"hasPhysics": true,
				"physicsMass": 100.0,
				"physicsRadius": 0.0,
"position": {"x": -5.568757, "y": -98.86594, "z": -5.876011},
"rotation": {"x": 355.8338, "y": 194.9597, "z": 182.385},
"normal": {"x": -0.0589419, "y": -0.9964935, "z": -0.05938448}
			}
		]
	},
"Spawn": {
    "shipSpawn":
    {
"position": {"x": -104.9429, "y": -150.7808, "z": -29.1422},
"rotation": {"x": 17.19935, "y": 141.6702, "z": 215.3437}
    }
    },
	"ReferenceFrame": {},
	"ShipLog": {
		"mapMode": {}
	},
	"ShockEffect": {}
}

### What was supposed to happen?

The ship is supposed to be spawned at the location that "shipSpawn" specifies

### Platform

Steam

### Mods

```Markdown
New Horizons and its dependencies, Unity Explorer, Cheats and Debug menu, and my own mod
```

**Comment by xen-42** [comment]
Old title was incorrect because ship spawns do work normally, this is just a very specific use case where they aren't working.
