### ISSUE TITLE
Title screen sizes don't reflect planet sizes

### ISSUE THREAD

**Issue by TerrificTrifid** [Outer-Wilds-New-Horizons/new-horizons#678]
### What Happened?

![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/99054745/7cad85c4-4064-46e0-9d3f-cbf637cd540c)
size is not considered, it makes everything the same full size, unless it has water or lava or something and then its half size

### What was supposed to happen?

It was completely fine until that one change half a year ago that added water/lava but also did this

### Platform

None

**Comment by xen-42** [comment]
Do it yourself

**Comment by MegaPiggy** [comment]
![:ghostNooo:](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/34462599/a4d7d3ff-be7a-44dc-a08f-a8339b541150)
