### ISSUE TITLE
Cloaks are still broken

### ISSUE THREAD

**Issue by xen-42** [Outer-Wilds-New-Horizons/new-horizons#682]
### What Happened?

- [ ] On Hearth's Neighbour you can see the Stranger cloak even if it's meant to be disabled
- [ ] In Divergence you can't mark ship log locations in cloak anymore

When fixing these things make sure that we don't break the Stranger cloak on the second loop (was an issue with the original cloak fix).

### Platform

None

**Comment by JohnCorby** [comment]
this shit really just doesnt end huh

**Comment by xen-42** [comment]
Nevermind the tesseract shit is ON PURPOSE???

**Comment by xen-42** [comment]
Cant recreate divergence issue

**Comment by xen-42** [comment]
This was all skill issues and/or was fixed
