### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by xen-42** [Outer-Wilds-New-Horizons/new-horizons#683]
Things that take a lot of time
- SearchUtilities.Find
- Loading asset bundles
- OWML logging
- PlanetDestructionHandler

Potential improvements
- [x] We should try caching root objects in SearchUtilities.
- [x] We should not unload asset bundles/textures until we leave the solar system they're used for.
  - I think we can do this for literally all the caches except ones that have references to things that get destroyed on scene transitions.
- [ ] We should add an option to not unload asset bundles/textures (faster loading times but will use more memory).
- [ ] We should reimplement log levels as a setting and default it to only log errors.
- [x] Create a mapping of bodies to their proxies so that we can disable them easier. Or, in their Initialize method patch it to destroy the proxy if the planet has been disabled, depending on when these things actually get set up (they are late initialized)

**Comment by JohnCorby** [comment]
loading asset bundles can be improved by the addon authors themselves, via their own code loading a bundle in the background on the title screen, or via not using compression

loading times for other systems was also significantly cut down by not using RemoveProxy

**Comment by xen-42** [comment]
Logging wasn't that big an issue, and never unloading bundles is yeah probably unneeded, creators can either optimize like john said or just set you to respawn in their system
