### ISSUE TITLE
Becoming immortal in Origins mod because of NH

### ISSUE THREAD

**Issue by hearth1an** [Outer-Wilds-New-Horizons/new-horizons#703]
### What Happened?

After starting new game and becoming linked to the statue, character becomes invincible bc of NH. 

### Platform

None

### Mods

```Markdown
Unity explorer and all NH dependencies
```

### Logs

```Shell
New Horizons

Log : Scene Loaded: SolarSystem Single OWScene.SolarSystem

New Horizons

Log : Toggling immortality: True
```

**Comment by xen-42** [comment]
In Main we should listen for "ResetSimulation" on the GlobalMessager, from this we flag a bool to be read the next time the solar system scene loads that will set _playerAwake and PlayerSpawned (both in Main.cs) to true.

**Comment by xen-42** [comment]
Alternatively if (loopCount == 1 && PlayerData.KnowsLaunchCodes()) we can set these bools to true when the scene loads
