### ISSUE TITLE
NRE in NHSupernovaPlanetEffectController

### ISSUE THREAD

**Issue by xen-42** [Outer-Wilds-New-Horizons/new-horizons#737]
### What Happened?

NullReferenceException: Object reference not set to an instance of an object
Stacktrace: NewHorizons.Components.Props.NHSupernovaPlanetEffectController.Update () (at C:/GitHub/new-horizons/NewHorizons/Components/Props/NHSupernovaPlanetEffectController.cs:228)

### Platform

None

**Comment by JohnCorby** [comment]
line is https://github.com/Outer-Wilds-New-Horizons/new-horizons/blob/main/NewHorizons/Components/Props/NHSupernovaPlanetEffectController.cs#L228

one of the ambient lights is null. potentially destroyed?
