### ISSUE TITLE
Lighting stops working from certain angles

### ISSUE THREAD

**Issue by Vector-Graphics** [Outer-Wilds-New-Horizons/new-horizons#743]
### What Happened?

![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/62966659/d2e1ac33-aabe-4228-a20a-7a49978bdf48)
From certain angles, my planet appears to have no light on it, including ambient light (but not including lightning effects). This appears to only happen in map mode (though I'm not sure). The outer and inner cloud layers and the ground were affected, but not the water surface. Every so often it shifts in or out of having no light, as seen here. This is in a separate system to the main one, so no sun conflicts are causing this. The planet's semi-major axis is 29 km. 

### What was supposed to happen?

The lighting on the planet is supposed to work normally.

### Platform

Steam

### Mods

```Markdown
New Horizons, Cheat and Debug Menu, Common Camera Utility, Custom Ship Log Modes, Light Bramble, Menu Framework, Vanilla Fix
```

**Comment by Vector-Graphics** [comment]
[xen.NewHorizons (2).zip](https://github.com/Outer-Wilds-New-Horizons/new-horizons/files/13032947/xen.NewHorizons.2.zip)
Here are my configs and textures (put the texture folder as "textures" in "Assets")

**Comment by Vector-Graphics** [comment]
ignore "A306 configs.zip"

**Comment by xen-42** [comment]
[planets.zip](https://github.com/Outer-Wilds-New-Horizons/new-horizons/files/13033308/planets.zip)
Changed it to not use the NH assets folder for whoever else tries to fix this

Definitely does have some weird lighting effects in the map

**Comment by Vector-Graphics** [comment]
![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/62966659/732d7c55-b52e-4a6a-8084-a03ef510b2fc)
Very weird graphical corruptions that I believe to be parallel to whatever line the lighting stops working beyond.

**Comment by JohnCorby** [comment]
map thing is known issue of 1.17.1 https://discord.com/channels/929708786027999262/929722485291753512/1159977618758709268

perhaps the lighting thing is also 1.17.1?

**Comment by xen-42** [comment]
Did this get fixed? The map graphics thing did at least

**Comment by xen-42** [comment]
Seems to be fixed, feel free to reopen with more pics and repro steps if it still occurs for you.
