### ISSUE TITLE
Slide Reels are inversed on the shiplog

### ISSUE THREAD

**Issue by pikpik-carrot** [Outer-Wilds-New-Horizons/new-horizons#746]
### What Happened?

slide reels are white and black not black and white
![(1)](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/100093626/b436bc1e-acc2-4967-af9f-1d81da5054a5)
![OuterWilds_jOAL8PHapi](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/100093626/cde9cffe-28d0-4f80-8aec-4bd237719a1e)
![Owlk_park_slide_0001](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/100093626/bd11a8bf-3a96-4104-91ce-8ebfc872d277)

https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/100093626/266a0c4a-b907-403c-9063-770952265cdd

[owlk_fun.json](https://github.com/Outer-Wilds-New-Horizons/new-horizons/files/13061712/owlk_fun.json)

### What was supposed to happen?

They are meant to be black and white no white and black

### Platform

None

### Mods

```Markdown
Auto Resume
Cheat and Debug Menu
Common Camera Utility
Custom Ship Log Modes
Menu Framework
New Horizons
Save Editor
Time Saver
Unity Explorer
Vanilla Fix
My mod
Divergence
```

**Comment by JohnCorby** [comment]
solution to this is setting SlideCollection.streamingAssetIdentifier to something non null, since it's accessed with a null check.

**Comment by JohnCorby** [comment]
waiting for pr, probably by me. just to remind myself
