### ISSUE TITLE
NH trailmarkers have no collision

### ISSUE THREAD

**Issue by bruvin-sky** [Outer-Wilds-New-Horizons/new-horizons#753]
### What Happened?

Just a small nitpick I noticed, no collision on these guys

### What was supposed to happen?

Pokemon wall bump sound

### Platform

None

**Comment by xen-42** [comment]
Not able to reproduce this, they have collisions for me. Can you share a config?

**Comment by xen-42** [comment]
Gonna close this since we can't reproduce it, feel free to reopen the issue with a config if you are still having the issue
