### ISSUE TITLE
thrusterStrength Volume

### ISSUE THREAD

**Issue by mrwallace888** [Outer-Wilds-New-Horizons/new-horizons#776]
### Feature

A volume to determine the total strength of your ship's thrusters. Would be set as a multiplier like with Cheats Mod.

Unless this is what thrustRulesets is _supposed_ to do, which it doesn't. I don't actually know what it's supposed to do, it's set to Infinity by default and I don't really notice any difference except it doesn't give me enough thrust to take off on a planet at lower values (almost like it just limits the max input or something) and it doesn't feel like it limits your actual speed (which speedTrap could theoretically already do anyways).

**Comment by xen-42** [comment]
ThrustRuleset is a base game class, we did not implement it. It's specifically only for the jetpack and to nerf your jetpack booster.

**Comment by JohnCorby** [comment]
like ur other issue, we dont really wanna add more custom functionality to nh. the current thing is just a limiter, because thats all base game has
