### ISSUE TITLE
Incompatibility with `PacificEngine.OW_CommonResources`

### ISSUE THREAD

**Issue by elenakrittik** [Outer-Wilds-New-Horizons/new-horizons#790]
### What Happened?

PacificEngine's CheatsMod depends on the above-mentioned mod, which means that it is impossible to use in worlds made using New Horizons (this happened to me with The Vision mod, specifically).

### What was supposed to happen?

I didn't expect an incompatibility here.

### Platform

None

### Mods

The problem occurs when you try to install and enable the following mods:
- `hearth1an.TheVision`
- `PacificEngine.CheatsMod`

### Logs

Not applicable.

![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/77104725/56a8b6dd-902a-47ea-9866-1a38b749c13d)

This incompatibility first appeared in #105, then expanded in #498. There isn't any reviews/conversations/notes on why they are incompatible.

**Comment by Bwc9876** [comment]
Common Resources re-implements a lot of orbital physics and other mechanics from the base game, making it extremely difficult / outright impossible to work with in NH. Even though cheats mod itself doesn't redefine these CR does as other PacificEngine mods like randomizer need it to. We'd recommend using [Cheat and Debug Menu](https://outerwildsmods.com/mods/cheatanddebugmenu/) as an alternative to CR as that doesn't mess with core parts of the game's code.

**Comment by elenakrittik** [comment]
Alright, thank you!
