### ISSUE TITLE
More distinguishable startup popups

### ISSUE THREAD

**Issue by JohnCorby** [Outer-Wilds-New-Horizons/new-horizons#791]
### Feature

People often skip the startup popups as a habit from skipping the vanilla reduced frights one.

perhaps we add a timer before it can be closed, or give it a different (maybe configurable?) accent color to stand out more.

### Context
![Discord Context](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/34462599/0bfb233c-9d41-411c-9756-7b29bbf5e82e)
https://discord.com/channels/929708786027999262/939019445605646357/1210817572388208670

**Comment by xen-42** [comment]
This would need to be done in OWML instead, I think, and then we just expose those options in addon-config.json

**Comment by xen-42** [comment]
Closing this because its an OWML issue not an NH one
