### ISSUE TITLE
Time Loop still occurs when disabling the ATP

### ISSUE THREAD

**Issue by CantAffordaName** [Outer-Wilds-New-Horizons/new-horizons#796]
### What Happened?

When the Advanced Warp Core is removed from the Ash Twin Project, the time loop still happens 50 seconds after the supernova occurs. This results in getting the "You Are Dead" ending even when far away from the sun, preventing players from achieving some endings that happen post-supernova.
It should be noted that on the Quantum Moon's sixth location, the sun does not go supernova and the correct ending plays.

### What was supposed to happen?

Disabling the ATP should allow for all possible endings to be achieved, like the Isolation ending or The Stranger ending. This would also allow for custom endings for NH mods that involve ending the time loop.

### Platform

Steam

### Mods

```Markdown
Cheat and Debug, Common Camera Utility, Custom Ship Log Modes, Menu Framework, New Horizons, OWFixPluginTypesSerialization, Save Editor, Static Camera, Unity Explorer, Vanilla Fix
```

**Comment by xen-42** [comment]
This guy had OWFixPluginTypesSerialization on

I'd blame that if I hadnt seen the bug myself with it off, will investigate
