### ISSUE TITLE
Generate basic sphere colliders for items/sockets

### ISSUE THREAD

**Issue by Hawkbat** [Outer-Wilds-New-Horizons/new-horizons#799]
### Feature

OWItems and OWItemSockets are targeted using raycasts against their colliders, rather than InteractVolumes or another method. This means that they cannot be interacted with if the detail being spawned doesn't have colliders already set up. To cover this use case, we should add a `radius` property to the item/itemSocket objects of details that adds a sphere collider with the specified radius, if it's greater than zero.

We should also take into account how this would interact with `hasPhysics` and `physicsRadius` which already does this. We should probably reuse the same collider if it has already been added by the other builder.

**Comment by JohnCorby** [comment]
hasPhysics is actually fundamentally incompatible with items, as they will drop from your hands as soon as you pick them up.

therefore, we do not have to actually worry about the interactions between the 2 options.

**Comment by Hawkbat** [comment]
Fixed by PR #806
