### ISSUE TITLE
Add "Dark Zones" to the "Volumes" module

### ISSUE THREAD

**Issue by CrypticBird** [Outer-Wilds-New-Horizons/new-horizons#822]
### Feature

Dark Zones are used frequently in the base game (see TH's Nomai Mine) and it would be nice to place them with NH

**Comment by xen-42** [comment]
Nope

**Comment by bruvin-sky** [comment]
it's not a 100% darkness volume (tho you can try change that with code)
but the path TimberHearth_Body/Sector_TH/Sector_RadioTower/RadioTower_noDLC/OcclusionEffects_Grove/OcclusionVolume_RadioTower is the best path I think I've found that works just as a path (the others break for some reason), comes in a clean square shape, and doesn't require DLC
