### ISSUE TITLE
anglerfish make planets go gorp unless the planet is invulnerabletosun

### ISSUE THREAD

**Issue by JohnCorby** [Outer-Wilds-New-Horizons/new-horizons#830]
cuz angler has fluid in mouth and planet detects that fluid

**Comment by xen-42** [comment]
I'd like to see somebody put an anglerfish on the interloper and watch if it goes gorp (itd go gorp I bet)

Because then nuh uh its not a bug its vanilla! And we'd just need to document this behaviour, and also rename InvulnerableToSun to be like "HasFluidDetector"
