### ISSUE TITLE
Weird xbox issues

### ISSUE THREAD

**Issue by xen-42** [Outer-Wilds-New-Horizons/new-horizons#838]
### What Happened?

DLC not installed flag lies to you on the microsoft version, also they had a weird issue with ship logs:

Install Astral Codec, learn all ship logs
Uninstall all mods
Relaunch base game without mods
Install the vision
Launch game -> all ship logs for the mod were already known

### Platform

None

**Comment by JohnCorby** [comment]
is this the thing where microsoft says NotReady for a bit before then saying you have it or dont

**Comment by xen-42** [comment]
One guy reported this once and then never again so I'm CLOSING it because nobody owns this game on Xbox nobody can reproduce this
