### ISSUE TITLE
subtitles start cycling before the main menu is visible

### ISSUE THREAD

**Issue by pikpik-carrot** [Outer-Wilds-New-Horizons/new-horizons#844]
The subtitles start cycling before the main menu is visible (like it starts on the splash screen or whatever).

see [here](https://github.com/pikpik-carrot/ThePulsar/blob/main/ThePulsar/SubtitlesHandlerPatch.cs) for fix.

**Comment by xen-42** [comment]
Ok why dont you make a PR then!

**Comment by MegaPiggy** [comment]
We can't see the fix because it is from your private repo pikpik
