### ISSUE TITLE
Allow HourglassTwins marker type without invoking the FocalPoint machinery

### ISSUE THREAD

**Issue by tgiddings** [Outer-Wilds-New-Horizons/new-horizons#847]
### Feature

It is my understanding that MarkerType.HourglassTwins is what allows the marker to disappear when viewed up close in the map. This would be useful for any named cluster of objects where the individual markers would clash when viewed from afar. However, currently the only code path in New Horizons that sets this checks for the FocalPoint configuration, and this configuration also overrides the gravity settings of the body it's applied to and the orbit settings of the bodies referenced as primary and secondary. 

### Context

Consider the following example. It would not be possible to rework "Equilateral Trinary" to use FocalPoint, since the gravity would be too small and none of the bodies are 180 degrees apart. I would like to be able to add a configuration to "Equilateral Trinary" which results in its map marker popping out at the same time that the map markers for the individual bodies pop in.
```
{
    "name": "Equilateral Trinary",
    "$schema": "https://raw.githubusercontent.com/Outer-Wilds-New-Horizons/new-horizons/main/NewHorizons/Schemas/body_schema.json",
    "starSystem": "SolarSystem",
    "Base": {
        "surfaceSize": 1,
        "surfaceGravity": 3636,
        "soiOverride": 0,
        "hasMapMarker": true
    },
    "Orbit": {
        "semiMajorAxis": 13000,
        "primaryBody": "SUN",
        "isTidallyLocked": true
    }
}
```
```
{
    "name": "Trinary 1",
    "$schema": "https://raw.githubusercontent.com/Outer-Wilds-New-Horizons/new-horizons/main/NewHorizons/Schemas/body_schema.json",
    "starSystem": "SolarSystem",
    "Base": {
        "groundSize": 100,
        "surfaceSize": 101,
        "surfaceGravity": 12,
        "hasMapMarker": true
    },
    "Orbit": {
        "semiMajorAxis": 700,
        "primaryBody": "Equilateral Trinary",
        "isMoon": true
    }
}
```
```
{
    "name": "Trinary 2",
    "$schema": "https://raw.githubusercontent.com/Outer-Wilds-New-Horizons/new-horizons/main/NewHorizons/Schemas/body_schema.json",
    "starSystem": "SolarSystem",
    "Base": {
        "groundSize": 100,
        "surfaceSize": 101,
        "surfaceGravity": 12,
        "hasMapMarker": true
    },
    "Orbit": {
        "semiMajorAxis": 700,
        "primaryBody": "Equilateral Trinary",
        "isMoon": true,
        "trueAnomaly": 120
    }
}
```
```
{
    "name": "Trinary 3",
    "$schema": "https://raw.githubusercontent.com/Outer-Wilds-New-Horizons/new-horizons/main/NewHorizons/Schemas/body_schema.json",
    "starSystem": "SolarSystem",
    "Base": {
        "groundSize": 100,
        "surfaceSize": 101,
        "surfaceGravity": 12,
        "hasMapMarker": true
    },
    "Orbit": {
        "semiMajorAxis": 700,
        "primaryBody": "Equilateral Trinary",
        "isMoon": true,
        "trueAnomaly": 240
    }
}
```

**Comment by xen-42** [comment]
Does this not achieve what you want to do here, under the Orbit module
![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/22628069/c8f93750-7671-4b44-b3dd-c4f9f45cdd74)

**Comment by MegaPiggy** [comment]
> Does this not achieve what you want to do here, under the Orbit module ![image](https://private-user-images.githubusercontent.com/22628069/326223061-c8f93750-7671-4b44-b3dd-c4f9f45cdd74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjkxNzcsIm5iZiI6MTcxNDI2ODg3NywicGF0aCI6Ii8yMjYyODA2OS8zMjYyMjMwNjEtYzhmOTM3NTAtNzY3MS00YjQ0LWIzZGQtYzRmOWY0NWNkZDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDAxNDc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyYWY4YTc0MGRkYTBhM2RlNzkyMTUwZTk2MGQ0M2Q1M2Q2NzUzY2Q2ZWEyMjAyYWM5YzJhMDZhYzRlOTY0ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GlvslwZ60107Gdn0ggM_dcRvSstgYARgnT9sKBbbBxI) Think the wording on these is a bit confusing, but I think if `Equilateral Trinary` had its fade start distance equal to the fade end distance of the other 3 it'd do what you're trying to achieve, right?

That is different. He is talking about the map markers that show the name of the object.
https://github.com/Outer-Wilds-New-Horizons/new-horizons/blob/e0a28557e207e51e829c7cced0f03ea9b5520499/NewHorizons/Builder/General/MarkerBuilder.cs#L18-L39

The display distances for the markers depend on the type
```csharp
switch (_markerType)
{
    case MarkerType.Planet:
    case MarkerType.Ship:
    case MarkerType.Probe:
        _maxDisplayDistance = 50000f;
        break;
    case MarkerType.HourglassTwins:
        _maxDisplayDistance = 50000f;
        _minDisplayDistance = 5000f;
        break;
    case MarkerType.ShipLog:
        _maxDisplayDistance = 50000f;
        _disableMapMarker = true;
        break;
    case MarkerType.Sun:
        _maxDisplayDistance = 1E+10f;
    case MarkerType.Moon:
    default:
        _maxDisplayDistance = 5000f;
        break;
    case MarkerType.Player:
        _maxDisplayDistance = 0f;
        break;
}
```

**Comment by tgiddings** [comment]
@MegaPiggy is correct about what I'm wanting. Name markers clash and create visual noise much more readily than orbit lines.

Also, the behavior of `orbitLineFadeEndDistance` and `orbitLineFadeStartDistance` are backwards from their descriptions. `orbitLineFadeEndDistance` caused the orbit line to fade when close.
