### ISSUE TITLE
ReuseDialogueOptionsFrom doesn't work for Chert

### ISSUE THREAD

**Issue by omega-fallon** [Outer-Wilds-New-Horizons/new-horizons#858]
### What Happened?

When adding new dialogue to Chert (I am doing this by manually calling CreateDialogueFromXML in a ChertDialogueSwapper postfix), ReuseDialogueOptionsFrom fails to work, simply doing nothing at all.

### What was supposed to happen?

Dialogue options were meant to be copied over.

### Platform

Steam

### Mods

```Markdown
[
  "Glitch.AltDebugMenu",
  "OmegaFallon.ReactiveHearthians",
  "SBtT.GeneralEnhancements",
  "dgarro.CustomShipLogModes",
  "Owen_013.FirstPersonPresence",
  "xen.CommonCameraUtility",
  "Kentin.SupernovaOnDemand",
  "Acamaeda.Shortcut",
  "SBtT.CameraShake",
  "_nebula.GlobalScreenSpaceReflections",
  "xen.AchievementTracker",
  "xen.NewHorizons",
  "JohnCorby.VanillaFix",
  "Bwc9876.SaveEditor",
  "VioVayo.HugMod",
  "dgarro.SuitLog",
  "clubby789.OWClock",
  "xen.SignalsPlus"
]
```

**Comment by xen-42** [comment]
Any errors in the logs? Could you maybe supply a project that causes this to happen so we can test it easier

**Comment by xen-42** [comment]
Ah, replacing dialogue takes 2 frames, and you're doing this on start conversation

**Comment by xen-42** [comment]
This limitation of NH will be documented in the next release. In ReactiveHearthians, what might work is checking the dialogue conditions in an Update method, manually calling SelectMood in advance, then creating the dialogue, and updating the `dialogueTextAsset` in the ChertConditionalDialogue array after the new dialogue has been made.
