### ISSUE TITLE
Hearthians deload even when scout is watching them

### ISSUE THREAD

**Issue by bruvin-sky** [Outer-Wilds-New-Horizons/new-horizons#889]
### What Happened?

Hearthians and travelers disappear once the player leaves their planet, even if a scout is left next to them and monitoring them. It's a minor but pretty immersion breaking bug

### What was supposed to happen?

Stay loaded if scout is watching them and not disappear (unless the whole game was just in the player's head and the hearthians and travelers are all just visions from the Eye too headexplosionemoji)

### Platform

None

**Comment by MegaPiggy** [comment]
Does this happen in vanilla? If so, then make an issue on https://github.com/JohnCorby/ow-vanilla-fix instead.
