### ISSUE TITLE
check that nh slides look correct

### ISSUE THREAD

**Issue by JohnCorby** [Outer-Wilds-New-Horizons/new-horizons#899]
Reel_2_Story slides have some slides that are inverted and some that are not inverted. we should use these to check that our code is correct

- [x] checking our invert algorithm vs theirs

**result: ours is brighter :(**

1. get base game slide for Reel_2_Story (in cinder isles) to see `Slide_2_Story_01_01.png`
2. put `Slide_2_Story_01_Vision_01.png` on a nh slide
3. see if they look the same (that means the way we invert is the same as way they invert)

- [x] (less important) check vision vs non vision
1. use the non inverted slide (like `Slide_2_Story_01_Vision_01.png`) on a vision torch (standing or target)
2. use the inverted slide (like `Slide_2_Story_01_01.png`) on a reel
3. check that they look the same on both

**Comment by AnonymousStrangerOW** [comment]
now that i see this issue, i did notice that my nh-generated reels are brighter than base game's, and i would have to darken the images themselves to achieve a similar brightness as base game.

here i attached an example reel from echoes of the eye i reimported into the game through new horizons. you may notice the darker images look more natural when inserted into the projector, but are dark on the actual reel model.
[Homeworld.zip](https://github.com/user-attachments/files/17260002/Homeworld.zip)

**Comment by JohnCorby** [comment]
nh slide reel
![image](https://github.com/user-attachments/assets/0406c278-9af9-4332-b31c-7e0d02ae3da1)

base game slide reel
![image](https://github.com/user-attachments/assets/3cbdac27-de2e-49b6-b0b7-cf8a692b66f8)

**Comment by JohnCorby** [comment]
vision torch is a much more direct png to in-game transition. we dont have to do anything to make it look right there

**Comment by JohnCorby** [comment]
ive decided that the current thing nh does (darkening images via marking them as linear) is a good enough. it could darken them in different ways, but its fine

the goal should be to make the in game slides match the source pngs. making them match base game is secondary because base game _severely_ darkens the source image, which we shouldnt make users do
