### ISSUE TITLE
bramble music fix/feature

### ISSUE THREAD

**Issue by AnonymousStrangerOW** [Outer-Wilds-New-Horizons/new-horizons#914]
### Feature

- [ ] when bramble music was released, it was still rather limited. it only changed the bramble music system-wide, and not for each individual dimension. this becomes problematic if you want to add nodes to the solar system without changing the music inside dark bramble. fixing the "2 songs overlapping at once" issue that currently happens when you place an audio volume in a bramble dimension could also work.

### Context

splitting these issue into parts for the convenience of the nh dev team

**Comment by MegaPiggy** [comment]
If you want individual music for each node just use an audio volume and it should override the system wide music

**Comment by AnonymousStrangerOW** [comment]
yeah it doesn't work. i've tried it, but it overlaps with the dark bramble theme anyway.

**Comment by xen-42** [comment]
Ideally we make the bramble music turn off when u enter another audio volume

Just to double check can you show the config that you tried the audio volume thing with

**Comment by AnonymousStrangerOW** [comment]
shit i forgot to close this a long time ago! turns out this was just a mishearing (the bg audio has dark bramble overlayed on it so i thought it was just being played with it). false alarm!

**Comment by MegaPiggy** [comment]
😮‍💨
