### ISSUE TITLE
Configs get loaded more than once if parent body is updated again

### ISSUE THREAD

**Issue by MegaPiggy** [Outer-Wilds-New-Horizons/new-horizons#921]
### What Happened?

If the primary body that a custom moon orbits is updated, the custom moon also gets updated again.
Problem with that is it will add everything that is already on it again. 
Which can get quite extreme if you have multiple configs updating the primary body.
Here is one moon config with 6 planet configs. There should not be 6 ground spheres and orbit lines, but because it gets reupdated 6 times that happens.
![6](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/34462599/4707986f-4fb9-4d87-972c-efe8e3d75311)

Here's an example mod with only 2 planet configs
[MegaPiggy.MultipleLoadBug.zip](https://github.com/user-attachments/files/16170429/MegaPiggy.MultipleLoadBug.zip)

### What was supposed to happen?

Should only load a config once

**Comment by xen-42** [comment]
whar
