### ISSUE TITLE
Cloud emission map

### ISSUE THREAD

**Issue by Minecraft633** [Outer-Wilds-New-Horizons/new-horizons#931]
### Feature

Pretty self explainitory, basically emission map support for CloudInfo, useful for custom storms.

### Context

Example map ([Planet 9 Night map by ItzImCool](https://www.deviantart.com/itzimcool/art/Planet-9-Night-Texture-Map-1032443927)):
![planet9_night_texturemap](https://github.com/user-attachments/assets/0766176b-4fcc-4aca-be83-a059fd8e9a03)

**Comment by xen-42** [comment]
Since this isn't something in the base game and can be better done just in Unity, I think you should just make a sphere in a unity project and assign your own material with emission textures.
