### ISSUE TITLE
option to remove fog from bramble dimension

### ISSUE THREAD

**Issue by AnonymousStrangerOW** [Outer-Wilds-New-Horizons/new-horizons#945]
### Feature

- [ ] adds boolean option to dimension configs to remove fog

### Context

additional question: do bramble dimension fog alphas actually alter the fog's opacity? because i swear it doesn't from my experiences using the nh framework.

**Comment by xen-42** [comment]
Set fogDensity to 0! fog alphas do not do anything yes. I'll update the descriptions to include this.
