### ISSUE TITLE
time loop re-enabled, even when warping to system with the vessel

### ISSUE THREAD

**Issue by AnonymousStrangerOW** [Outer-Wilds-New-Horizons/new-horizons#952]
### What Happened?

- [ ] stop time loop from activating at the end of a loop when in a new horizons system after warping to it with the vessel (which requires you to disable the atp)

### What was supposed to happen?

i was supposed to die at the end of the loop instead of getting sent back in time by the ash twin project

### Platform

Steam

### Mods

```Markdown
- new horizons & its dependencies
```

**Comment by xen-42** [comment]
If you warp with the vessel back to Dark Bramble and travel to the ATP, is the warp core still gone?

**Comment by AnonymousStrangerOW** [comment]
### What Happened?

i warped to the vessel, opened cheats and debug's clock with the tilde (~) key, and noticed the clock was still counting down to the end of the loop.

### What was supposed to happen?

the clock should be static or at least identical to the eye's output (starting from 0:00 and going into negatives), and the time loop shouldn't be happening.
![image](https://github.com/user-attachments/assets/c764fb19-f779-4237-8b67-88ffd4247549)


### Platform

Steam

### Mods

```Markdown
"_nebula.MenuFramework",
  "Locochoco.ColliderVisualizer",
  "AnonymousStrangerOW.TheStrangerTheyAre",
  "Glitch.AltDebugMenu",
  "Anyar.CustomAnglerfishAI",
  "Bwc9876.SaveEditor",
  "Vesper.UnityExplorer",
  "xen.CommonCameraUtility",
  "JohnCorby.VanillaFix",
  "JohnCorby.OWFixPluginTypesSerialization",
  "Switch.BringMeMyShip",
  "dgarro.CustomShipLogModes",
  "misternebula.FreeCam",
  "Bwc9876.TimeSaver",
  "VioVayo.DWModAssist",
  "dgarro.SuitLog",
  "xen.NewHorizons",
  "xen.EyeHelper",
  "Alek.LightBramble"
```
