### ISSUE TITLE
Warping to DB in vessel kills me

### ISSUE THREAD

**Issue by xen-42** [Outer-Wilds-New-Horizons/new-horizons#959]
Seems to be due to impact, something is wrong with the spawn location or the player velocity perhaps.

To reproduce: Vessel warp to NH examples (grab the AWC at spawn and use Cheat and Debug warp number 140 to get to vessel immediately). Now vessel warp back.

**Comment by AnonymousStrangerOW** [comment]
i can confirm, this happens.

https://github.com/user-attachments/assets/7157de23-092a-45ff-9784-8eaf09cbd0ff

**Comment by AnonymousStrangerOW** [comment]
to reproduce: warp to custom nh system, warp back to outer wilds, both with the vessel.

**Comment by xen-42** [comment]
Okay it stopped happening so idk i win
