### ISSUE TITLE
Astral Codec's "Translation Probe Thicket" gets semi-deleted by The Outsider

### ISSUE THREAD

**Issue by Ixrec** [Outer-Wilds-New-Horizons/new-horizons#966]
- [X] Fix missing signal
- [ ] Fix missing scroll
- [ ] Fix missing detail (probe)

### What Happened?

When running both The Outsider and Astral Codec at the same time:

1) The Translation Probe Thicket signal is not visible

Intended behavior when just Astral Codec (+ Cheat & Debug) is running:
![image](https://github.com/user-attachments/assets/2f42b193-cd42-40e7-a374-c3ce029a3f3c)

Incorrect behavior when The Outsider + Astral Codec (+ Cheat & Debug) are running:
![image](https://github.com/user-attachments/assets/2949508d-125f-4830-b15e-873f4aacccca)

2) The probe itself is often invisible (when I first mentioned this in Discord it was visible, but not any more)

![image](https://github.com/user-attachments/assets/3b7c19ba-249b-455e-b129-4909ed1d24bd)

The "Unidentified Signal Nearby" notification always works, but trying to scan the signal does not. The probe is also still solid, and still projects holograms when you pick up the nearby scroll, etc, so you could say it's "mostly there".

3) The green scroll on the nearby bench is also often invisible (I wasn't checking this before so maybe it always was?)

![image](https://github.com/user-attachments/assets/9810aeab-69c9-47d1-96bd-83a0274b134d)

but interacting with it still works fine.

### What was supposed to happen?

Ideally, the mods would peacefully coexist without such senseless violence against innocent probes.

Of course this goes way beyond what most mods are expected to support, but it would be nice if this "just worked" when my randomizer is randomizing both of these mods (and more). On Discord xen said it'd be "nice to have that not happen", so it's at least worth recording in an issue.

For the time being, my randomizer will be working around this by checking for the Unidentified Signal Nearby state instead of the signal being scanned, and warning the player about these invisible things when they have both mods installed.

### Platform

Steam

### Mods

I've tested this with several sets of mods, and I'm pretty sure the minimum needed to reproduce is just Astral Codec, The Outsider and their direct dependencies.

But in case it matters, the "maximum" mod set I run with during rando development these days (and thus what some of these screenshots were taken with) is
```json
[
  "dgarro.CustomShipLogModes",
  "dgarro.SuitLog",
  "Ixrec.ArchipelagoRandomizer",
  "SBtT.TheOutsider",
  "clubby789.OWClock",
  "Walker.AstralCodex",
  "GameWyrm.HearthsNeighbor",
  "Heelio.EotEBrighterDreams",
  "Glitch.AltDebugMenu",
  "xen.NewHorizons",
  "JohnCorby.VanillaFix",
  "xen.CommonCameraUtility",
  "Vesper.UnityExplorer",
  "xen.EnableMeditation",
  "MegaPiggy.OWRichPresence"
]
```

### Logs

I haven't found any unique error messages in the logs on wakeup, on Signalscope usage, or on walking up to the probe.

**Comment by Ixrec** [comment]
Thanks for fixing the signal!

Unfortunately the probe and the scroll are still invisible.

![image](https://github.com/user-attachments/assets/e35ec997-d6ae-42c2-a704-402efc6bb0aa)

Should we reopen this issue or make a new one?

**Comment by xen-42** [comment]
They work for me

**Comment by xen-42** [comment]
Okay fine I'll double check

**Comment by xen-42** [comment]
![image](https://github.com/user-attachments/assets/41e5b430-08e6-4e4c-9317-b3409984c1c3)

The sky in your screenshot looks different, did you just not visit the chime yet?
