### ISSUE TITLE
Can't join dream world via dying

### ISSUE THREAD

**Issue by SamuelSVargas** [Outer-Wilds-New-Horizons/new-horizons#972]
### What Happened?

Simple as it says, when I have New Horizons loaded in I am unable to join the dream world by jumping in the campfire and dying, but other methods are still functional.
This happens even when jus NEw Horizons is loaded in.

### Platform

Steam

### Mods

```Markdown
xen.CommonCameraUtility
xen.NewHorizons
dgarro.CustomShipLogModes
JohnCorby.VanillaFix
```

**Comment by Hawkbat** [comment]
Fixed in v1.23.4 👍
