### ISSUE TITLE
Making a planet its own Primary Body causes an infinite load

### ISSUE THREAD

**Issue by GameWyrm** [Outer-Wilds-New-Horizons/new-horizons#983]
### What Happened?

I copied a planet file over to use as said planet's moon but forgot to update the name field, so NH thought the file was for the base planet. I had remembered to set the Primary Body of the new file, so now the file had both the Name and Primary Body fields as the same value. This resulted in NH getting stuck on "Updating body PlanetName" and the game never loading.

### What was supposed to happen?

NH should recognize that a planet is not supposed to be its own primary body and should refuse to load the planet file.

### Platform

Steam

### Logs

```Shell
[New Horizons.NHLogger] : Log : Creating [PlanetName]
[New Horizons.NHLogger] : Log : Updating existing Object PlanetName_Body
```

**Comment by xen-42** [comment]
skill issue
